export const CATEGORIAS_FORNECEDOR = [
  'A&B — Alimentos & Bebidas',
  'Buffet',
  'Local de realização',
  'Audiovisual — Som, iluminação, projeção',
  'Captação ao vivo / Streaming',
  'Decoração',
  'Cenografia',
  'Flores / Arranjos florais',
  'Mobiliário / Locação de móveis',
  'Tendas / Estruturas temporárias',
  'Kits e materiais do participante',
  'Brindes / Merchandising',
  'Gráfica / Impressão / Sinalização',
  'Transporte / Transfer / Logística',
  'Hospedagem / Hotel',
  'Estacionamento / Valet',
  'Fotografia / Filmagem',
  'Cerimonial / Mestre de cerimônias',
  'Entretenimento / Artistas / Shows',
  'Credenciamento / Recepção',
  'Segurança / Brigadistas',
  'Saúde / Médico / Ambulância',
  'Limpeza / Higienização',
  'Internet / Conectividade',
  'Energia / Gerador',
  'Tecnologia / Sistemas / Software',
  'Tradução / Interpretação',
  'Marketing / Comunicação',
  'Assessoria / Consultoria',
] as const
